spring.application.name=productSolution
server.port=8200
#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/productSolution
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# session timeout in minutes (example: 15 minutes)
server.servlet.session.timeout=10m

# Allow bigger file uploads
# For both images & videos
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thakurdeepesh045@gmail.com
spring.mail.password=nvpy vbvm kfcf cpbb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


