spring.application.name=productSolution
server.port=${PORT:8080}
#database configuration
spring.datasource.url=jdbc:postgresql://dpg-d6pppk1j16oc73bk50og-a.singapore-postgres.render.com:5432/productsolution
spring.datasource.username=productuser
spring.datasource.password=4qjsiy44LIWM2fY5pV8OlKyeqv7XIrc3

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# session timeout in minutes (example: 15 minutes)
server.servlet.session.timeout=10m

# Allow bigger file uploads
# For both images & videos
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thakurdeepesh045@gmail.com
spring.mail.password=nvpy vbvm kfcf cpbb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


